### ISSUE TITLE
Deploy automático

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-mobile#37]
El objetivo es tener un comando para deployar al PlayStore

Investigar
- https://www.npmjs.com/package/publish-aab-google-play (npm)
- https://docs.fastlane.tools/ (Ruby)

**Comment by ivojawer** [comment]
https://dev.to/zenika/deploy-react-native-app-on-playstore-with-fastlane-and-github-actions-2-2-5gnc
https://github.com/antoinecellier/rn-fastlane-githubactions/
