### ISSUE TITLE
App crashea en Android

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-mobile#39]
Al correr los tests la App se cierra con `Fatal signal 6`. Esto es porque [el UI thread se bloquea](https://stackoverflow.com/questions/36693887/what-is-fatal-signal-6-in-android-logcat).

Probar si con esto se arregla: https://github.com/joltup/react-native-threads

-----

**EDIT** (30/01/2022)
- `react-native-threads` se quedó en el tiempo y surgen varios problemas para instalarlo (hay que pelear con el build de RN que te cambia el código de los Packages de Java)
- Estuvimos logueando dónde está el problema con Wollok-TS y llegamos a que:
  - Probamos usar un _ExecutionDirector_ con un `setInterval` para darle next "de a pasitos".
  - Hay problemas al crear la Evaluation: se rompe al crear todos los Singletons.
  - Zafando de eso (solamente creando el objeto `assert`), hay un problema de que la versión de JS no tiene implementado soporte para las `WeakRef` que se usan para la cache de Literales.
- Otra alternativa sería ejecutar en una view de un navegador (que es otro proceso) usando: https://www.npmjs.com/package/@cawfree/react-native-elsewhere (tiene problemas con Hermes)

**Comment by ivojawer** [comment]
**SUPUESTAMENTE** cambiar la version de ecmascript en reactnative solo deberia ser cambiar archivo _.babelrc_

```json
{
  "presets": ["es2020"]
}
```

**Comment by PalumboN** [comment]
Al final el problema venía de que la versión de Android no tiene WeakRef, la hackeamos haciendo una implementación (de mentira) propia.
