### ISSUE TITLE
No dejar crear entidades sin nombre 

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-mobile#5]
Si ahora creo una entidad y nunca le pongo nombre la crea sin problemas, lo que es raro, estaría bueno que no pase.

**EDIT**: Ahora también pasa que si agregás un Describe sin nombre y entrás para ponerle tests te muestra la pantalla de la definición de un objeto (supongo que es porque se accede por fqn, y no tener nombre rompe el fqn).

![Screenshot_20210526-123134_Wollok.jpg](https://user-images.githubusercontent.com/4098184/119690439-11b15f80-be20-11eb-8ee5-6f985bd9726f.jpg)

Se podría poner una validación en los diálogos de creación, que te avise que le tenés que poner un nombre.

**Comment by ivojawer** [comment]
Todo el tema de validacion se va a empezar a repetir bastante. 

Encontre esta libreria que la version angular esta bastante buena. https://www.npmjs.com/package/react-reactive-form, es bastante independiente de lo visual cosa que para mi es un gran plus

Esta tambien https://formik.org/docs/guides/react-native

**Comment by PalumboN** [comment]
Ojo hay 2 niveles de validaciones:
- Las del modelo, que las hace Wollok en base a las reglas que él propone para trabajar (por ejemplo, que las clases empiecen en mayus). Son validaciones que queremos en todos los Wolloks del mundo.
- Las de vista, que se harían acá y están vinculadas a cosas que se muestran o cómo están pensadas las pantallas.

Justo esta es una de las validaciones que podríamos tener en ambos lados:
- Debería ser una validación de Wollok, porque no tiene sentido semántico crear por ejemplo objetos nombrados sin nombre.
- También podría ser de la vista, porque la forma que tenemos de mostrar las entidades es a través de su nombre.

Lo que decís aplica a las validaciones de la vista, y me parece bien cualquier cosa que decidas. Igual esto es ponerle un `required` al campo, no creo que haga falta mucha logística. Pero si querés probar alguna de esas cosas no me opongo (nunca las usé, así que no aportar mucho).

Más allá de eso, deberíamos tener una forma de ejecutar las validaciones de Wollok-TS y mostrarlas. Se me ocurre tener algún icono arriba a la derecha, que se corra cada vez que hacés un cambio. Similar a los IDEs, que abra un panel cuando lo clickeas:
![Peek 2021-08-21 17-23](https://user-images.githubusercontent.com/4098184/130333991-f9e1b6d7-9181-4708-8964-6c191fd9e5bf.gif)

Esto último ya se encuentra en https://github.com/uqbar-project/wollok-mobile/issues/41

**Comment by PalumboN** [comment]
⚠️ Otra cosa que pasa, es que cuando creas una entidad (con un nombre) y después creas otra sin nombre se vuelve a crear con el último nombre.

**Comment by PalumboN** [comment]
Ahora también deja crear entidades con el mismo nombre, habría que correr las validaciones de Wollok y va a saltar la chafi

**Comment by PalumboN** [comment]
Hacer los Inputs required parece no ser tan fácil en RN. Mirar https://blog.echobind.com/react-hook-form-for-react-native-912c45282718

**Comment by PalumboN** [comment]
Resuelto en #92
